project:
  type: website
  output-dir: docs
  resources:
    - html/*
    - help/*

website:
  title: testpkg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: packageWebsiteInstructions.qmd
        text: Detailed Instructions
      - text: Vignettes
        menu:
          - href: vignettes/test1.Rmd
            text: Vignette 1
          - href: vignettes/test2.Rmd
            text: Vignette 2
      - href: html/00Index.html
        text: Manual

  sidebar:
    style: "docked"
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - packageWebsiteInstructions.qmd
      # - section: "Manual Pages"
      #   contents: man/myfun.html
format:
  html:
    theme: yeti
    css: styles.css
    toc: true



